"""Initial revision

Revision ID: 18c94642806b
Revises: 
Create Date: 2026-08-04 14:34:15.224370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c94642806b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_symbol', sa.String(length=30), nullable=False),
    sa.Column('yf_symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('instrument_token', sa.Integer(), nullable=True),
    sa.Column('asset_class', sa.Enum('EQUITY', 'ETF', 'INDEX', name='assetclass', native_enum=False), nullable=False),
    sa.Column('is_index', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_symbol', 'exchange_id', name='_symbol_exchange_uc')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_trading_symbol'), 'symbols', ['trading_symbol'], unique=False)
    op.create_table('index_constituents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_symbol_id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['index_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_symbol_id', 'stock_symbol_id', name='_index_stock_uc')
    )
    op.create_index(op.f('ix_index_constituents_id'), 'index_constituents', ['id'], unique=False)
    op.create_table('market_data_eod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'date', name='_symbol_date_eod_uc')
    )
    op.create_index('idx_eod_symbol_date', 'market_data_eod', ['symbol_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_data_eod_date'), 'market_data_eod', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_eod_id'), 'market_data_eod', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_eod_symbol_id'), 'market_data_eod', ['symbol_id'], unique=False)
    op.create_table('market_data_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'date', name='_symbol_date_history_uc')
    )
    op.create_index('idx_history_symbol_date', 'market_data_history', ['symbol_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_data_history_date'), 'market_data_history', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_history_id'), 'market_data_history', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_history_symbol_id'), 'market_data_history', ['symbol_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'SL', 'SL_M', name='ordertype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'COMPLETE', 'CANCELLED', 'REJECTED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus', native_enum=False), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    # ### end Alembic commands ###
    
    # 2. Seed Benchmark Symbols
    op.execute("""
        INSERT INTO symbols (exchange_id, trading_symbol, name, yf_symbol, asset_class, is_index, is_active)
        SELECT 
            e.id, 
            idx.trading_symbol, 
            idx.name, 
            idx.yf_symbol, 
            'INDEX',
            TRUE,
            TRUE
        FROM (
            VALUES 
                ('NSE', 'NIFTY 50', 'Nifty 50 Index', '^NSEI'),
                ('NSE', 'NIFTY 500', 'Nifty 500 Index', '^CRSLDX'),
                ('NASDAQ', 'S&P 500', 'S&P 500 Index', '^GSPC'),
                ('NASDAQ', 'NASDAQ 100', 'NASDAQ 100 Index', '^NDX'),
                ('NASDAQ', 'RUSSELL 2000', 'Russell 2000 Index', '^RUT')
        ) AS idx(exchange_code, trading_symbol, name, yf_symbol)
        JOIN exchanges e ON e.code = idx.exchange_code
        ON CONFLICT (exchange_id, trading_symbol) DO UPDATE 
        SET yf_symbol = EXCLUDED.yf_symbol, 
            asset_class = EXCLUDED.asset_class,
            is_active = TRUE;
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_data_history_symbol_id'), table_name='market_data_history')
    op.drop_index(op.f('ix_market_data_history_id'), table_name='market_data_history')
    op.drop_index(op.f('ix_market_data_history_date'), table_name='market_data_history')
    op.drop_index('idx_history_symbol_date', table_name='market_data_history')
    op.drop_table('market_data_history')
    op.drop_index(op.f('ix_market_data_eod_symbol_id'), table_name='market_data_eod')
    op.drop_index(op.f('ix_market_data_eod_id'), table_name='market_data_eod')
    op.drop_index(op.f('ix_market_data_eod_date'), table_name='market_data_eod')
    op.drop_index('idx_eod_symbol_date', table_name='market_data_eod')
    op.drop_table('market_data_eod')
    op.drop_index(op.f('ix_index_constituents_id'), table_name='index_constituents')
    op.drop_table('index_constituents')
    op.drop_index(op.f('ix_symbols_trading_symbol'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
    # Remove seeded benchmark indices on rollback
    op.execute("""
        DELETE FROM symbols 
        WHERE trading_symbol IN ('NIFTY 50', 'NIFTY 500', 'S&P 500', 'NASDAQ 100', 'RUSSELL 2000');
    """)
