"""add_entry_date_and_initial_quantity_to_holdings

Revision ID: d19e48aded2b
Revises: 0a9d3e1ee45c
Create Date: 2026-08-31 13:27:24.815618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d19e48aded2b"
down_revision: Union[str, Sequence[str], None] = "0a9d3e1ee45c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add columns as nullable
    op.add_column("holdings", sa.Column("entry_date", sa.Date(), nullable=True))
    op.add_column(
        "holdings", sa.Column("initial_quantity", sa.Integer(), nullable=True)
    )

    # Step 2: Backfill existing rows using current values
    op.execute("""
        UPDATE holdings 
        SET entry_date = COALESCE(updated_at::date, CURRENT_DATE),
            initial_quantity = COALESCE(quantity, 0)
        WHERE entry_date IS NULL;
    """)

    # Step 3: Enforce NOT NULL constraint
    op.alter_column("holdings", "entry_date", nullable=False)
    op.alter_column("holdings", "initial_quantity", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("holdings", "entry_date")
    op.drop_column("holdings", "initial_quantity")
    # ### end Alembic commands ###
