NSE_CONFIG = {
    "output_dir": "C:/work/AutoTrading/Claude/live_results",
    "start_date": None,
    "end_date": None,
    "starting_capital": 1000000.0,
    "rs_rank_threshold": 70,
    "min_pct_above_52w_low": 0.3,
    "max_pct_below_52w_high": 0.25,
    "pivot_order": 3,
    "min_base_days": 15,
    "min_contractions": 2,
    "max_base_age_days": 90,
    "entry_discount": 0.025,
    "volume_mult": 1.25,
    "risk_pct_per_trade": 0.010,
    "hard_stop_pct": 0.05,
    "trailing_stop_pct": 0.08,
    "profit_take_pct": 0.2,
    "profit_take_fraction": 0.5,
    "min_avg_volume": 50000,
    "as_of_date": None,
    "current_equity": 1000000.0,
    "market_health_method": "ema_confirmed",
    "market_health_ema_fast": 8,
    "market_health_ema_slow": 21,
    "market_health_ema_confirm_days": 3,
}

SP_CONFIG = {
    "output_dir": "C:/work/AutoTrading/Claude/live_results",
    "start_date": None,
    "end_date": None,
    "starting_capital": 1000000.0,
    "rs_rank_threshold": 70,
    "min_pct_above_52w_low": 0.3,
    "max_pct_below_52w_high": 0.25,
    "pivot_order": 3,
    "min_base_days": 15,
    "min_contractions": 2,
    "max_base_age_days": 90,
    "entry_discount": 0.025,
    "volume_mult": 1.25,
    "risk_pct_per_trade": 0.010,
    "hard_stop_pct": 0.05,
    "trailing_stop_pct": 0.08,
    "profit_take_pct": 0.2,
    "profit_take_fraction": 0.5,
    "min_avg_volume": 50000,
    "as_of_date": None,
    "current_equity": 1000000.0,
    "market_health_method": "ema_confirmed",
    "market_health_ema_fast": 8,
    "market_health_ema_slow": 21,
    "market_health_ema_confirm_days": 3,
}
